name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Adicione/Atualize este passo para garantir o Node 22
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4 # Atualizei para v4 que é melhor para Node 22
        with:
          version: 9 # Versão recomendada para projetos atuais

      - name: Install, build, and upload
        uses: withastro/action@v3
        with:
          path: .
          package-manager: pnpm@9
